Update pre-commit configuration
thoth-station/mi pull request #524
Opened 2022-02-14 16:13 UTC by codificat

## Related Issues and Dependencies

- Triggered by https://github.com/thoth-station/thoth-application/issues/2111

## This introduces a breaking change

- No

## This should yield a new module release

- No

## This Pull Request implements

Use https instead of git for the plugins, and update the versions of the base image and plugins in use.

2022-02-14 16:14 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmi).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/mi/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2022-02-14 19:18 UTC, harshad16 requested changes
lgtm
just one comment to fix pytest.

2022-02-14 19:26 UTC, codificat commented on .prow.yaml
> +        - image: quay.io/thoth-station/thoth-pytest:v0.14.3
ah, ok, thanks!

2022-02-15 11:32 UTC, xtuchyna commented
thx!

/approve

2022-02-16 13:11 UTC, harshad16 approved these changes
lgtm
thanks :100:

2022-02-16 13:12 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/mi/pull/524#pullrequestreview-884514148" title="Approved">harshad16</a>*, *<a href="https://github.com/thoth-station/mi/pull/524#issuecomment-1040166182" title="Approved">xtuchyna</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmi).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/mi/blob/master/OWNERS)~~ [xtuchyna]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-02-16 13:20 UTC, merged